#!/usr/bin/env php
<?php

declare(strict_types=1);

require 'vendor/autoload.php';
require __DIR__ . '/app/load-env.php';

use DI\ContainerBuilder;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

$containerBuilder = new ContainerBuilder();

$cache = require __DIR__ . '/app/cache.php';
$cache($containerBuilder);

$entityManager = require 'app/doctrine.php';
$entityManager($containerBuilder);

$container = $containerBuilder->build();

$entityManager = $container->get(EntityManager::class);

ConsoleRunner::run(
    new SingleManagerProvider($entityManager),
);
